// tslint:disable
/**
 * fit-shopify-data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI, throwIfNullOrUndefined } from '../runtime';
import type { OperationOpts, HttpHeaders, HttpQuery } from '../runtime';
import type {
    FulfillmentStatus,
    OrderOutput,
} from '../models';

export interface GetOrdersRequest {
    from: string;
    to: string;
    xFitToken?: string | null;
    fulfillmentStatus?: FulfillmentStatus;
}

/**
 * no description
 */
export class OrderControllerApi extends BaseAPI {

    /**
     */
    getOrders({ from, to, xFitToken, fulfillmentStatus }: GetOrdersRequest): Observable<Array<OrderOutput>>
    getOrders({ from, to, xFitToken, fulfillmentStatus }: GetOrdersRequest, opts?: OperationOpts): Observable<AjaxResponse<Array<OrderOutput>>>
    getOrders({ from, to, xFitToken, fulfillmentStatus }: GetOrdersRequest, opts?: OperationOpts): Observable<Array<OrderOutput> | AjaxResponse<Array<OrderOutput>>> {
        throwIfNullOrUndefined(from, 'from', 'getOrders');
        throwIfNullOrUndefined(to, 'to', 'getOrders');

        const headers: HttpHeaders = {
            ...(xFitToken != null ? { 'x-fit-token': String(xFitToken) } : undefined),
        };

        const query: HttpQuery = { // required parameters are used directly since they are already checked by throwIfNullOrUndefined
            'from': (from as any).toISOString(),
            'to': (to as any).toISOString(),
        };

        if (fulfillmentStatus != null) { query['fulfillmentStatus'] = fulfillmentStatus; }

        return this.request<Array<OrderOutput>>({
            url: '/orders',
            method: 'GET',
            headers,
            query,
        }, opts?.responseOpts);
    };

}
