// tslint:disable
/**
 * fit-shopify-data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    RestockType,
} from './';

/**
 * @export
 * @interface OrderLineOutput
 */
export interface OrderLineOutput {
    /**
     * @type {number}
     * @memberof OrderLineOutput
     */
    shopify_id: number;
    /**
     * @type {string}
     * @memberof OrderLineOutput
     */
    sku: string;
    /**
     * @type {string}
     * @memberof OrderLineOutput
     */
    title: string;
    /**
     * @type {number}
     * @memberof OrderLineOutput
     */
    product_id: number;
    /**
     * @type {number}
     * @memberof OrderLineOutput
     */
    variant_id: number;
    /**
     * @type {string}
     * @memberof OrderLineOutput
     */
    variant_title?: string | null;
    /**
     * @type {boolean}
     * @memberof OrderLineOutput
     */
    refunded: boolean;
    /**
     * @type {RestockType}
     * @memberof OrderLineOutput
     */
    restock_type: RestockType;
    /**
     * @type {number}
     * @memberof OrderLineOutput
     */
    quantity: number;
    /**
     * @type {number}
     * @memberof OrderLineOutput
     */
    price: number;
    /**
     * @type {number}
     * @memberof OrderLineOutput
     */
    total_discount: number;
    /**
     * @type {number}
     * @memberof OrderLineOutput
     */
    total_tax: number;
    /**
     * @type {number}
     * @memberof OrderLineOutput
     */
    total_price: number;
}
