// tslint:disable
/**
 * fit-shopify-data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    PriceSetInput,
    TaxLineInput,
} from './';

/**
 * @export
 * @interface OrderLineInput
 */
export interface OrderLineInput {
    /**
     * @type {number}
     * @memberof OrderLineInput
     */
    id: number;
    /**
     * @type {string}
     * @memberof OrderLineInput
     */
    sku: string;
    /**
     * @type {string}
     * @memberof OrderLineInput
     */
    title: string;
    /**
     * @type {number}
     * @memberof OrderLineInput
     */
    product_id: number;
    /**
     * @type {number}
     * @memberof OrderLineInput
     */
    variant_id: number;
    /**
     * @type {string}
     * @memberof OrderLineInput
     */
    variant_title?: string | null;
    /**
     * @type {number}
     * @memberof OrderLineInput
     */
    quantity: number;
    /**
     * @type {PriceSetInput}
     * @memberof OrderLineInput
     */
    price_set: PriceSetInput;
    /**
     * @type {PriceSetInput}
     * @memberof OrderLineInput
     */
    total_discount_set: PriceSetInput;
    /**
     * @type {Array<TaxLineInput>}
     * @memberof OrderLineInput
     */
    tax_lines: Array<TaxLineInput>;
}
