// tslint:disable
/**
 * fit-shopify-data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface ProductVariantInput
 */
export interface ProductVariantInput {
    /**
     * @type {number}
     * @memberof ProductVariantInput
     */
    id: number;
    /**
     * @type {string}
     * @memberof ProductVariantInput
     */
    title?: string | null;
    /**
     * @type {string}
     * @memberof ProductVariantInput
     */
    sku: string;
    /**
     * @type {number}
     * @memberof ProductVariantInput
     */
    inventory_quantity: number;
    /**
     * @type {number}
     * @memberof ProductVariantInput
     */
    grams: number;
    /**
     * @type {string}
     * @memberof ProductVariantInput
     */
    price: string;
    /**
     * @type {string}
     * @memberof ProductVariantInput
     */
    compare_at_price?: string | null;
    /**
     * @type {string}
     * @memberof ProductVariantInput
     */
    created_at: string;
    /**
     * @type {string}
     * @memberof ProductVariantInput
     */
    updated_at: string;
}
