// tslint:disable
/**
 * fit-shopify-data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    ProductImageInput,
    ProductStatusInput,
    ProductVariantInput,
} from './';

/**
 * @export
 * @interface ProductInput
 */
export interface ProductInput {
    /**
     * @type {number}
     * @memberof ProductInput
     */
    id: number;
    /**
     * @type {string}
     * @memberof ProductInput
     */
    title: string;
    /**
     * @type {string}
     * @memberof ProductInput
     */
    handle: string;
    /**
     * @type {ProductStatusInput}
     * @memberof ProductInput
     */
    status: ProductStatusInput;
    /**
     * @type {string}
     * @memberof ProductInput
     */
    created_at: string;
    /**
     * @type {string}
     * @memberof ProductInput
     */
    updated_at: string;
    /**
     * @type {string}
     * @memberof ProductInput
     */
    published_at?: string | null;
    /**
     * @type {Array<ProductImageInput>}
     * @memberof ProductInput
     */
    images: Array<ProductImageInput>;
    /**
     * @type {string}
     * @memberof ProductInput
     */
    tags: string;
    /**
     * @type {Array<ProductVariantInput>}
     * @memberof ProductInput
     */
    variants: Array<ProductVariantInput>;
}
