// tslint:disable
/**
 * fit-shopify-data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface ProductVariantOutput
 */
export interface ProductVariantOutput {
    /**
     * @type {number}
     * @memberof ProductVariantOutput
     */
    shopify_id: number;
    /**
     * @type {string}
     * @memberof ProductVariantOutput
     */
    title?: string | null;
    /**
     * @type {string}
     * @memberof ProductVariantOutput
     */
    sku: string;
    /**
     * @type {number}
     * @memberof ProductVariantOutput
     */
    inventory_quantity: number;
    /**
     * @type {number}
     * @memberof ProductVariantOutput
     */
    weight: number;
    /**
     * @type {number}
     * @memberof ProductVariantOutput
     */
    price: number;
    /**
     * @type {number}
     * @memberof ProductVariantOutput
     */
    compare_at_price?: number | null;
    /**
     * @type {string}
     * @memberof ProductVariantOutput
     */
    created_date_time: string;
    /**
     * @type {string}
     * @memberof ProductVariantOutput
     */
    updated_date_time: string;
}
