// tslint:disable
/**
 * fit-shopify-data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    ProductStatusOutput,
    ProductVariantOutput,
} from './';

/**
 * @export
 * @interface ProductOutput
 */
export interface ProductOutput {
    /**
     * @type {number}
     * @memberof ProductOutput
     */
    shopify_id: number;
    /**
     * @type {string}
     * @memberof ProductOutput
     */
    title: string;
    /**
     * @type {string}
     * @memberof ProductOutput
     */
    handle: string;
    /**
     * @type {string}
     * @memberof ProductOutput
     */
    main_image_url: string;
    /**
     * @type {ProductStatusOutput}
     * @memberof ProductOutput
     */
    status: ProductStatusOutput;
    /**
     * @type {string}
     * @memberof ProductOutput
     */
    created_date_time: string;
    /**
     * @type {string}
     * @memberof ProductOutput
     */
    updated_date_time: string;
    /**
     * @type {string}
     * @memberof ProductOutput
     */
    published_date_time?: string | null;
    /**
     * @type {Array<string>}
     * @memberof ProductOutput
     */
    tags: Array<string>;
    /**
     * @type {Array<ProductVariantOutput>}
     * @memberof ProductOutput
     */
    variants: Array<ProductVariantOutput>;
}
