// tslint:disable
/**
 * fit-shopify-data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface StatsOutput
 */
export interface StatsOutput {
    /**
     * @type {string}
     * @memberof StatsOutput
     */
    from: string;
    /**
     * @type {string}
     * @memberof StatsOutput
     */
    to: string;
    /**
     * @type {number}
     * @memberof StatsOutput
     */
    number_of_orders: number;
    /**
     * @type {number}
     * @memberof StatsOutput
     */
    average_order_value: number;
    /**
     * @type {number}
     * @memberof StatsOutput
     */
    total_order_value: number;
    /**
     * @type {number}
     * @memberof StatsOutput
     */
    average_shipping_value: number;
    /**
     * @type {number}
     * @memberof StatsOutput
     */
    total_shipping_value: number;
    /**
     * @type {number}
     * @memberof StatsOutput
     */
    average_order_weight?: number | null;
    /**
     * @type {number}
     * @memberof StatsOutput
     */
    total_order_weight: number | null;
    /**
     * @type {number}
     * @memberof StatsOutput
     */
    number_of_order_lines: number;
    /**
     * @type {number}
     * @memberof StatsOutput
     */
    average_order_line_value: number;
    /**
     * @type {number}
     * @memberof StatsOutput
     */
    total_order_line_value: number;
}
